### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Vexot** [nightcycle/synthetic#2]
I think it would be easier to document synthetic using open-source tools like [Docusaurus](https://docusaurus.io/) and [MK Docs](https://squidfunk.github.io/mkdocs-material/). These are customizable and provide a lot of features.

Also the link provided on the README isn't valid, the actual link is https://nightcycle.github.io/synthetic/intro

**Comment by nightcycle** [comment]
I agree, if you check some of the code I'm actually mid-porting it to moonwave. My plan was to publish it to the link once it was ready.

**Comment by nightcycle** [comment]
Published the new documentation

**Comment by Vexot** [comment]
Great! I'll look into it
